"""
Django settings for chocolatier_core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r%+ncl4ms=nt(9#cffn!v*72lrc^9dv6e7b*_of2^$qy7cvzp*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # DjangoのREST Frameworkの読み込むためのもの。(DjangoのAPI開発のために指定するもの。固定値。)
    'chocolatier_api', # アプリ名を追加
    'corsheaders',
    'rest_framework_simplejwt', #JWT
]

# ミドルウェア：すべてのリクエスト／レスポンスが「上から順に」通過する処理
# - CorsMiddleware はレスポンスに CORS ヘッダー（Access-Control-Allow-*）を付ける
# - CommonMiddleware などがリダイレクト等のレスポンスを先に返してしまうと
#   CORS ヘッダーが付かずブラウザでエラーになるため、できるだけ上に置く
#   （以前はリストの末尾にあった）
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # CommonMiddleware より前に置く
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chocolatier_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chocolatier_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS設定
# - React（localhost:3000）と Django（localhost:8000）はポートが違う＝別オリジンなので、
#   ブラウザは Django 側が許可しない限り API のレスポンスを JS に渡さない
# - Cookie を使うため「全許可」は不可。React の開発サーバーだけ許可する
#   （ブラウザの仕様で、Cookie 付きの通信は Access-Control-Allow-Origin: * を受け付けない）
CORS_ALLOWED_ORIGINS = ['http://localhost:3000']
# Cookie の送受信を許可（Access-Control-Allow-Credentials: true を返す）
# - フロント側の axios の withCredentials: true とセットで必要
CORS_ALLOW_CREDENTIALS = True
# CSRF チェックで「信頼してよいリクエスト元」
# - Django は更新系リクエストの Origin ヘッダーも確認するため、React のオリジンを登録する
# - 登録しないと、CSRF トークンが正しくても 403（CSRF Failed: Origin checking failed）になる
CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']


# カスタムユーザーモデルの使用
AUTH_USER_MODEL = 'chocolatier_api.User'

# DRF（Django REST Framework）の共通設定
# - 全 API にデフォルトで適用される。View ごとに authentication_classes /
#   permission_classes を書くと、その View だけ上書きできる
REST_FRAMEWORK = {
    # 認証：「リクエストしてきたのは誰か」を判定する
    # - authentication.py の CookieJWTAuthentication で、Cookie の access_token を検証する
    # - 以前は simplejwt 標準の JWTAuthentication（Authorization ヘッダーを読む）だった
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'chocolatier_api.authentication.CookieJWTAuthentication',
    ),
    # 権限：「その人がこの API を使ってよいか」を判定する
    # - IsAuthenticated = ログイン必須。未ログインなら 401
    # - 以前は未設定（＝ AllowAny 扱い）で、誰でも全 API を使えてしまっていた
    # - ログイン・signup・refresh・logout・csrf は各 View で AllowAny にしている
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# 認証 Cookie の設定（views.py の set_auth_cookies / authentication.py で使う）
# - Cookie 名：ブラウザの DevTools > Application > Cookies にこの名前で表示される
AUTH_COOKIE_ACCESS = 'access_token'
AUTH_COOKIE_REFRESH = 'refresh_token'
# - Secure 属性：True だと HTTPS の通信でしか Cookie を送らない
#   開発は http なので False にしないと Cookie が送られない。本番(DEBUG=False)では自動で True
AUTH_COOKIE_SECURE = not DEBUG
# - SameSite 属性：別サイトから来たリクエストに Cookie を付けるかどうか
#   'Lax' は、別サイトからの POST や fetch には付けない（CSRF 攻撃の軽減）
#   localhost:3000 と localhost:8000 はポート違いでも「同じサイト」扱いなので、Lax でも送られる
AUTH_COOKIE_SAMESITE = 'Lax'

# アクセストークン有効期限 = 60分
# リフレッシュトークン有効期限 = 1日
# - Cookie の max_age もこの値に合わせている（views.py の set_auth_cookies）
# - access が切れたら、フロントの client.ts が自動で /token/refresh/ を呼ぶ
# - refresh も切れたら（1日）再ログインが必要
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# ファイルアップロード用
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')