# Generated by Django 5.2.5 on 2026-09-30 15:07

from django.db import migrations, models

# python manage.py makemigrations chocolatier_api
class Migration(migrations.Migration):

    dependencies = [
        ('chocolatier_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='snap',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snaps', to='chocolatier_api.tag'),
        ),
    ]
